version: '3.8'

services:
  dogbooks:
    build: ./app-restapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app-restapi/:/usr/src/app/
    ports:
      - 8001:8000
    env_file:
      - ./app-restapi/.env.dev
  dogbooks-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dogbooks
      - POSTGRES_PASSWORD=dogbooks
      - POSTGRES_DB=dogbooks_dev
# Bind postgres_data to the "/var/lib/postgresql/data/"
# directory in the container.
volumes:
  postgres_data: